[package]
name = "bcg/reworking-sim"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Observers = "sleitnick/observers@^0.3.3"
Knit = "sleitnick/knit@^1.7"